<a href="https://colab.research.google.com/github/saibaba/LinearAlgebra/blob/master/EigenAnalysisFibonacci.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Analyze fibonacci numbers via Eigenvectors
--------

Indirectly you also learn about diagonalization, spectral decomosition, low rank approximation, dyads!


Fibonacci numbers follow this rule:

$F_0 = 0$

$F_1 = 1$

$F_{n+1} = F_{n} + F_{n-1}$

Can we write this in matrix form?

$\begin{bmatrix} F_{n+1} \\\ F_{n} \end{bmatrix} = \begin{bmatrix} 1 & 1 \\\ 1 & 0 \end{bmatrix} * \begin{bmatrix} F_{n} \\\ F_{n-1} \end{bmatrix}$

Let $A =  \begin{bmatrix} 1 & 1 \\\ 1 & 0 \end{bmatrix}$.

By induction,

$\begin{bmatrix} F_{n+1} \\\ F_{n} \end{bmatrix} = {\begin{bmatrix} 1 & 1 \\\ 1 & 0 \end{bmatrix}}^2 * \begin{bmatrix} F_{n-1} \\\ F_{n-2} \end{bmatrix} = {\begin{bmatrix} 1 & 1 \\\ 1 & 0 \end{bmatrix}}^n * \begin{bmatrix} F_1 \\\ F_0 \end{bmatrix}$

Is there an easier way to take powers of A?

Given that it is square matrix, if we can convert into a diagonal matrix, taking power is easy as we just need to take powers of diagonal elements.

Let,

$A = Q D Q^{-1}$

Then,

$A Q = Q D$

Let $v_1$ and $v_2$ be two column vectors of $Q$ i.e., $Q = \begin{bmatrix} v_1 & v_2 \end{bmatrix}$.

Let $\lambda_1$ and $\lambda_2$ be the diagonal elements of $D$ i.e., $D = \begin{bmatrix} \lambda_1 & 0 \\\ 0 & \lambda_2 \end{bmatrix}$.

$A \begin{bmatrix} v_1 & v_2 \end{bmatrix} = \begin{bmatrix} v_1 & v_2 \end{bmatrix}  \begin{bmatrix} \lambda_1 & 0 \\\ 0 & \lambda_2 \end{bmatrix}$.

Hence,

$\begin{bmatrix} Av_1 & Av_2 \end{bmatrix} = \begin{bmatrix} \lambda_1 v_1 & \lambda_2 v_2 \end{bmatrix}$.

So, we want $v_1$ and $v_2$ be eigenvectors of A with diagonal elements as corresponding eigenvalues.

Also notice that A happens to be symmetric. Hence $A = A^T$.(understand what this means for the 4 spaces of A and $A^T$).

Then for any two vectors $x$ and $y$:

$A = A^T$

=> $Ax.y = y^T (Ax) = y^T (A^Tx) = (Ay)^T x = x.Ay$ 

If we take x = $v_1$ and y = $v_2$,

$\lambda_1 v_1.v_2 = \lambda_2 v_1.v_2$

If A is invertible (full rank), $\lambda_1 \ne \lambda_2$, hence $v_1$ must be perpendicular to $v_2$.

Let's solve for $v_1$, $v_2$, $\lambda_1$, and $\lambda_2$.

For any eigenvector $\begin{bmatrix} p \\\ q \end{bmatrix}$,

$\begin{bmatrix} 1 & 1 \\\ 1 & 0 \end{bmatrix} \begin{bmatrix} p \\\ q \end{bmatrix} = \lambda \begin{bmatrix} p \\\ q \end{bmatrix}$.

$p+q=\lambda p$ and $p = \lambda q$.

or

$\lambda q+q=\lambda^2 q$.

or

$\lambda + 1=\lambda^2$.

$\lambda^2 - \lambda - 1 = 0$.

$\lambda = \frac{1 \pm \sqrt(1 + 4)}{2} = \frac{1 \pm \sqrt(5)}{2}$

Let $\lambda_1 = \frac{1 + \sqrt(5)}{2}$ and $\lambda_2 = \frac{1 - \sqrt(5)}{2}$.

We can take arbitrarily $q = 1$, then $p = \lambda_1 q = \lambda_1$.

So, $v_1 = \begin{bmatrix} \lambda_1 \\\ 1 \end{bmatrix}$.

$v_2 = \begin{bmatrix} \lambda_2 \\\ 1 \end{bmatrix}$.

$Q = \begin{bmatrix} v_1 & v_2\end{bmatrix} = \begin{bmatrix} \lambda_1 & \lambda_2 \\\ 1 & 1 \end{bmatrix}$.

Also,

$det(Q) = \lambda_1 - \lambda_2 = \frac{1 + \sqrt(5)}{2} -  \frac{1 - \sqrt(5)}{2} = \sqrt(5)$.

$Q^{-1} = \frac{1}{\sqrt(5)} \begin{bmatrix} 1 & -\lambda_2 \\\ -1 & \lambda_1 \end{bmatrix} = \begin{bmatrix} \frac{1}{\sqrt(5)} & \frac{\sqrt(5)-1}{2\sqrt(5)} \\\ \frac{-1}{\sqrt(5)} & \frac{1+\sqrt(5)}{2\sqrt(5)} \end{bmatrix}$

Therefore,


$\begin{bmatrix} 1 & 1 \\\ 1 & 0 \end{bmatrix} = \begin{bmatrix} \lambda_1 & \lambda_2 \\\ 1 & 1 \end{bmatrix} * \begin{bmatrix} \lambda_1 & 0 \\\ 0 & \lambda_2 \end{bmatrix} * \begin{bmatrix} \lambda_1 & 1 \\\ \lambda_2 & 1 \end{bmatrix}$

$\begin{bmatrix} 1 & 1 \\\ 1 & 0 \end{bmatrix} = \begin{bmatrix} \frac{1 + \sqrt(5)}{2} &  \frac{1 - \sqrt(5)}{2} \\\ 1 & 1 \end{bmatrix} * \begin{bmatrix} \frac{1 + \sqrt(5)}{2} & 0 \\\ 0 & \frac{1 - \sqrt(5)}{2} \end{bmatrix} *  \begin{bmatrix} \frac{1}{\sqrt(5)} & \frac{\sqrt(5)-1}{2\sqrt(5)} \\\ \frac{-1}{\sqrt(5)} & \frac{1+\sqrt(5)}{2\sqrt(5)} \end{bmatrix}$

Hence $(n+1)^{th}$ and ${n}^{th}$ fibonacci number is given by this expression:


$\begin{bmatrix} F_{n+1} \\\ F_{n} \end{bmatrix} = {\begin{bmatrix} 1 & 1 \\\ 1 & 0 \end{bmatrix}}^n \begin{bmatrix} 1 \\\ 0 \end{bmatrix} = \begin{bmatrix} \frac{1 + \sqrt(5)}{2} &  \frac{1 - \sqrt(5)}{2} \\\ 1 & 1 \end{bmatrix} * {\begin{bmatrix} \frac{1 + \sqrt(5)}{2} & 0 \\\ 0 & \frac{1 - \sqrt(5)}{2} \end{bmatrix}}^n *  \begin{bmatrix} \frac{1}{\sqrt(5)} & \frac{\sqrt(5)-1}{2\sqrt(5)} \\\ \frac{-1}{\sqrt(5)} & \frac{1+\sqrt(5)}{2\sqrt(5)} \end{bmatrix} * \begin{bmatrix} 1 \\\ 0 \end{bmatrix}$



The three matrices on the right can be expanded (I am using $\lambda$'s for the sake of simplicity instead of actual values):

$\begin{bmatrix} \lambda_1 & \lambda_2 \\\ 1 & 1 \end{bmatrix} * \begin{bmatrix} \lambda_1^n & 0 \\\ 0 & \lambda_2^n \end{bmatrix} * \frac{1}{\sqrt(5)} \begin{bmatrix} 1 & -\lambda_2 \\\ -1 & \lambda_1 \end{bmatrix}$

Ignoring $\frac{1}{\sqrt(5)}$ for now,


$\begin{bmatrix} \lambda_1 & \lambda_2 \\\ 1 & 1 \end{bmatrix} * \begin{bmatrix} \lambda_1^n & -\lambda_1^n \lambda_2 \\\ -\lambda_2^n & \lambda_1 \lambda_2^n \end{bmatrix}$

$\begin{bmatrix} \lambda_1^{n+1} - \lambda_2^{n+1} & -\lambda_1^{n+1}  \lambda_2 + \lambda_1 \lambda_2^{n+1} \\\ \lambda_1^n -\lambda_2^n & -\lambda_1^n \lambda_2 + \lambda_1 \lambda_2^n \end{bmatrix}$


$\begin{bmatrix} \lambda_1^{n+1} & -(\lambda_1 \lambda_2)\lambda_1^{n}  \\\ \lambda_1^n & -(\lambda_1 \lambda_2) \lambda_1^{n-1} \end{bmatrix} + \begin{bmatrix} -\lambda_2^{n+1} & (\lambda_1 \lambda_2) \lambda_2^{n} \\\ -\lambda_2^n & (\lambda_1 \lambda_2) \lambda_2^{n-1} \end{bmatrix}$

$\lambda_1^n \begin{bmatrix} \lambda_1 & -\lambda_1 \lambda_2 \\\ 1 & -\lambda_2 \end{bmatrix} + \lambda_2^n \begin{bmatrix} -\lambda_2 & \lambda_1 \lambda_2 \\\ -1 & \lambda_1 \end{bmatrix}$

This can also be written as sum of rank 1 matrices using dyads:

$\lambda_1^n \begin{bmatrix} \lambda_1 \\\ 1 \end{bmatrix} \begin{bmatrix} 1 & -\lambda_2 \end{bmatrix} + \lambda_2^n \begin{bmatrix} \lambda_2 \\\ 1 \end{bmatrix} \begin{bmatrix} -1 & \lambda_1 \end{bmatrix}$

As n goes to infinity, since $\lambda_2 \lt 1$, the second term vanishes. In that case, above becomes, just

$\lambda_1^n \begin{bmatrix} \lambda_1 & -\lambda_1 \lambda_2 \\\ 1 & -\lambda_2 \end{bmatrix}$

Now, overall expression becomes,

$\begin{bmatrix} F_{n+1} \\\ F_{n} \end{bmatrix} = \frac{1}{\sqrt(5)}\lambda_1^n \begin{bmatrix} \lambda_1 & -\lambda_1 \lambda_2 \\\ 1 & -\lambda_2 \end{bmatrix} *  \begin{bmatrix} 1 \\\ 0 \end{bmatrix} = \frac{1}{\sqrt(5)}\lambda_1^n \begin{bmatrix} \lambda_1 \\\ 1 \end{bmatrix}$

And the ratio of successive terms = ${\lambda_1}$ = golden ratio.

And formula for approximate n-th term:

$F_{n} = \frac{1}{\sqrt(5)}\lambda_1^n = \frac{(1+\sqrt 5)^n}{2^n\sqrt 5}$.


Instead of starting with 0 and 1, if we start with arbitrary numbers a, b and follow the same principle (a, b, a+b, a+2b, 2a+3b ...):

$\begin{bmatrix} F_{n+1} \\\ F_{n} \end{bmatrix} = \frac{1}{\sqrt(5)}\lambda_1^n \begin{bmatrix} \lambda_1 & -\lambda_1 \lambda_2 \\\ 1 & -\lambda_2 \end{bmatrix} *  \begin{bmatrix} b \\\ a \end{bmatrix} = \frac{1}{\sqrt(5)}\lambda_1^n \begin{bmatrix} \lambda_1(b-\lambda_2 a) \\\ (b-\lambda_2 a) \end{bmatrix}$

So, the ratio of successive terms is still the golden ratio!

It is so golden!



A more direct way of doing the same is by writing $\begin{bmatrix} 1 \\\ 0 \end{bmatrix}$ as linear combination of eigenvectors, $v_1$ and $v_2$:

$\begin{bmatrix} 1 \\\ 0 \end{bmatrix} = av_1+bv_2$.

Then,

$\begin{aligned}
A^n \begin{bmatrix} 1 \\\ 0 \end{bmatrix}
&=   a A^n v_1 + b A^n v_2 \\\
&=   a \lambda_1^n v_1 + b \lambda_2^n v_2 \\\
&\approx   a \lambda_1^n v_1\end{aligned}$

(as the second term goes to zero in the long run)

Now to solve for a, and b:

$a \begin{bmatrix} \lambda_1 \\\ 1 \end{bmatrix} + b \begin{bmatrix} \lambda_2 \\\ 1 \end{bmatrix}$

$a \lambda_1 + b \lambda_2 = 0$

and

$ a + b = 0 $

$a = -b$

$a = \frac{1}{\lambda_1 - \lambda_2} = \frac{1}{\sqrt 5}$

$A^n \begin{bmatrix} 1 \\\ 0 \end{bmatrix} = \frac{1}{\sqrt 5} (\frac{1+\sqrt 5}{2})^n \begin{bmatrix} \lambda_1 \\\ 1 \end{bmatrix} = \frac{1}{\sqrt 5}  \begin{bmatrix} \lambda_1^{n+1} \\\ \lambda_1^n \end{bmatrix}$

Same as above.


In [0]:
import numpy as np
from numpy import linalg as LA

a = np.array([1, 1, 1, 0]).reshape((2, 2))
print(a)

[[1 1]
 [1 0]]


In [0]:
# A = Q D Q^T

def next_fib_naive(m, f):
    return m.dot(f)

def next_fib_diag(q, qinv, d, f):
    ef = qinv.dot(f)
    return q.dot(d.dot(ef))
    
s, v = LA.eig(a)

D = np.diag(s)
Qinv = v.T # also = LA.inv(v)
Q = v
print(Q)

print(D)
f0  = np.array([1, 0]).reshape((2, 1))

ef0 = Qinv.dot(f0)

print("-----")
print(Q.dot(D.dot(ef0)))

print("-----")

fi = f0
for i in range(10):
    fi = next_fib_naive(a, fi)
print(fi)

fi = f0
for i in range(10):
    fi = next_fib_diag(Q, Qinv, D, fi)
    
print(fi)

[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]
[[ 1.61803399  0.        ]
 [ 0.         -0.61803399]]
-----
[[1.]
 [1.]]
-----
[[89]
 [55]]
[[89.]
 [55.]]
